sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - cpanm --quiet --notest Test::CheckManifest
  - cpanm --quiet --installdeps --notest .
